### PR TITLE
Fixes for 0.7 and add some basic tests

### LINKED ISSUE #5: node reorganization breaks CSSUtil
After https://github.com/JuliaGizmos/WebIO.jl/pull/159 the following happens:

cssutil

The reason is that in WebIO `dom"div"(v::Vector)` changed behavior silently.

### PR DESCRIPTION
**Pull request by tkoolen**
Also fixes #5.

### CODE REVIEW

**Comment by tkoolen** [comment]
Alright, tests are passing on 0.6 again, and tests also pass on 1.0 (without depwarns) with:

* [x] https://github.com/vtjnash/Pidfile.jl/pull/2
* [ ] https://github.com/JuliaGizmos/WebIO.jl/pull/169

File: src/layout.jl [hunk 1]
```diff
@@ -23,7 +23,7 @@ function flex(elem=nothing)
     style(elem, "display"=>"flex")
 end
 
-function container(xs...)
+function container(xs::AbstractVector)
```
Comment (tkoolen) [inline src/layout.jl:26]: This was necessary because after the `Node` -> `node` change, this would otherwise create a `PersistentVector{Vector{Node}}` instead of a `PersistentVector{Node}`.

Comment (tkoolen) [reply src/layout.jl:26]: Ah, this fixes https://github.com/JuliaGizmos/CSSUtil.jl/issues/5.

Comment (piever) [reply src/layout.jl:26]: Nice! Probably worth adding a `container(xs...) = container([xs...])` method as well: this function is exported so we should try to preserve the multi-argument method.

File: test/runtests.jl [hunk 2]
```diff
@@ -1,5 +1,42 @@
 using CSSUtil
-using Base.Test
+using WebIO
+using Compat.Test
 
-# write your own tests here
-@test 1 == 1
+if isdefined(WebIO, :node) # TODO: remove once a new WebIO tag is in
```
Comment (piever) [inline test/runtests.jl]: It just got tagged, could you update this?

**Comment by tkoolen** [comment]
All done. Should I disallow failures on 1.0 on Travis?

**Comment by piever** [comment]
Yes, if it's already passing on 1.0 we don't need to allow failures. Other than that, LGTM.

Btw, you JuliaRobotics guys really are heroes, you and Robin have fixed so many things lately in the web stack!

**Comment by piever** [comment]
And one last thing: the README also needs to be updated to `node`

**Comment by tkoolen** [comment]
Thanks!

Addressed comments.

Just for clarity: to get CI to pass on 1.0 we still need the WebIO tag, but after that tag CSSUtil is good on 1.0.
